routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PrincipalController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [PrincipalController::class, 'principalBaterias'])->name('/');

Route::get('/teoria', [PrincipalController::class, 'teoria'])->name('teoria');

Route::get('/procedimento', [PrincipalController::class, 'procedimento'])->name('procedimento');

Route::get('/medicoes', [PrincipalController::class, 'medicoes'])->name('medicoes');

Route::get('/conclusoes', [PrincipalController::class, 'conclusoes'])->name('conclusoes');

Route::get('/principal', [PrincipalController::class, 'principal']);

Route::get('/pagina1', [PrincipalController::class, 'pagina1']);

Route::get('/pagina2', [PrincipalController::class, 'pagina2']);

app/Models/Medicoes.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class medicoes extends Model
{
    use HasFactory;
    public function getResistenciaInternaAttribute()
    {
        return $this->resistencia_carga*($this->tensao_sem_carga / $this->tensao_com_carga -1 );
    }
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/PrincipalController.php
<?php

namespace App\Http\Controllers;

use App\Models\Medicoes;
use Illuminate\Http\Request;

class PrincipalController extends Controller {

    public function principalBaterias(){
        return view('principalBaterias');
    }

    public function teoria(){
        return view('teoria');
    }

    public function procedimento(){
        return view('procedimento');
    }

    public function medicoes(){
        $medicoes = medicoes::all();
        return view('medicoes',compact('medicoes'));
    }

    public function conclusoes(){
        return view('conclusoes');
    }

    public function principal(){
        return view('principal');
    }

    public function pagina1() {
        return view('pagina1');
    }

    public function pagina2() {
        return view('pagina2');
    }

}

resources/views/conclusoes.blade.php
@extends('templates.base') 
@section('conteudo')
    




<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Baterias</title>


    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="../css/estilos.css">
</head>
<body>
    <header>
        <h1>Baterias</h1>
    </header>

    <nav>
        <ul>
            <li><a href="../index.html">voltar para página principal</a></li>
        </ul>
    </nav>

    <main>
        <h1>Conclusões</h1>
        <hr>
        <p>
         Concluir sobre medições de pilhas envolve reconhecer a importância de entender e monitorar o desempenho das baterias, bem como o papel fundamental das estruturas de dados "pilha" em ciência da computação.

No caso das pilhas elétricas (baterias), a medição adequada é essencial para garantir o funcionamento eficiente e seguro de dispositivos eletrônicos. Diferentes tipos de baterias têm características distintas, como capacidade, taxa de autodescarga e recarregabilidade. Medir a capacidade da bateria e monitorar a vida útil é crucial para determinar sua eficácia em diferentes aplicações. Além disso, a segurança é uma consideração importante ao utilizar e carregar baterias, especialmente as de íons de lítio, para evitar riscos de superaquecimento ou curto-circuito.

No contexto da ciência da computação, a estrutura de dados "pilha" é uma ferramenta fundamental para a resolução de problemas e implementação de algoritmos. É usada em várias situações, desde o gerenciamento de chamadas de funções (recursão) até a organização de ações em programas que necessitam de desfazer/refazer funcionalidade.

Em suma, a medição adequada das pilhas elétricas é essencial para garantir a segurança e eficiência em dispositivos eletrônicos. Por outro lado, a estrutura de dados "pilha" é uma ferramenta valiosa em ciência da computação, que permite resolver problemas de forma eficiente e ordenada. Compreender ambos os conceitos é essencial para um uso adequado e efetivo tanto na tecnologia do dia-a-dia quanto no desenvolvimento de software e algoritmos.
 Claro! As "pilhas" que você menciona podem se referir a dois conceitos diferentes: as pilhas elétricas (baterias) e a estrutura de dados "pilha" usada em ciência da computação. Vamos explicar ambos:

<h3> 1. Pilhas Elétricas (Baterias):</h3>
As pilhas elétricas, também conhecidas como baterias, são dispositivos que armazenam energia química e a convertem em energia elétrica quando necessária. Elas são amplamente utilizadas em diversos dispositivos eletrônicos, como smartphones, laptops, câmeras, relógios, entre outros.
<h2>Existem vários tipos de baterias, cada uma com características diferentes:</h2>        
<h5>Bateria alcalina: </h5><p>São pilhas não recarregáveis comuns em muitos dispositivos domésticos. Elas possuem uma boa capacidade, mas não são adequadas para uso repetido.
    

</p>
<h5>Bateria de íons de lítio (Li-ion):</h5>-  São amplamente usadas em dispositivos portáteis devido à sua alta densidade de energia e baixa taxa de autodescarga. Elas são recarregáveis e geralmente são seguras e duráveis.

<h5>Bateria de íons de lítio-polímero (Li-Po): </h5>- Também recarregáveis e usadas em dispositivos portáteis, essas baterias têm uma forma mais flexível e fina, o que permite que sejam moldadas para se encaixar em diferentes designs.

<h5> Bateria de níquel-cádmio (NiCd): </h5>- Embora menos comuns hoje em dia, essas baterias também são recarregáveis e são conhecidas por sua alta taxa de descarga, mas têm o efeito de memória, o que pode diminuir a capacidade ao longo do tempo se não forem carregadas corretamente.

<h5> Bateria de níquel-hidreto metálico (NiMH): </h5>- Também recarregáveis, essas baterias têm maior capacidade do que as baterias de NiCd e não possuem o problema de memória, mas podem sofrer com a autodescarga.

- Bateria alcalina: São pilhas não recarregáveis comuns em muitos dispositivos domésticos. Elas possuem uma boa capacidade, mas não são adequadas para uso repetido.

<h3> 2. Pilha (Estrutura de dados):</h3>
Em ciência da computação, uma pilha é uma estrutura de dados que segue o princípio "Last In, First Out" (LIFO), o que significa que o último elemento inserido é o primeiro a ser removido. É como uma pilha de pratos: você pode adicionar pratos (empilhar) somente no topo da pilha e retirar pratos apenas do topo da pilha.
  
As pilhas são amplamente utilizadas na programação e na resolução de problemas, como no gerenciamento de chamadas de funções (recursão), avaliação de expressões matemáticas, histórico de ações em navegadores, desfazer e refazer ações em editores de texto, entre outros.

     <H3> As operações básicas de uma pilha são:</H3>
      <ul>
        <li> <H5>Empilhar (push):  </H5>Adicionar um elemento no topo da pilha.</li>
        <li> <H5> Desempilhar (pop):  </H5>Remover o elemento do topo da pilha.</li>
        <li> <H5>Verificar o topo (top):  </H5>  Verificar o elemento no topo da pilha sem removê-lo.</li>
      </ul>
    </li>               
    
  
  


</p>
        <p>
            Aprendemos na pratica que as condições de um circuito elétrico não são perfeitas como na teoria. Os componentes do circuito não são os unicos no proprio a conterem um nível de resistência elétrica,
            essa resistência também é encontrada internamente na fonte dependendo de qual ela seja.
        </p>
    </main>
</body>
</html>
@endsection

@section('rodape')
    
<h4>Conclusões</h4>

@endsection 

resources/views/medicoes.blade.php
@extends('templates.base') 
@section('conteudo') 

    <main>
        <h1>Medições</h1>
        <hr>
        <h2>Valores obtidos:</h2>
        <table class="table table-striped table-bordered" id="tbDados">
            <thead>
            <tr>
                <th>Pilha/Bateria</th>
                <th>Tensão nominal (V)</th>
                <th>Capacidade de corrente (mA.h)</th>
                <th>Tensão sem carga(V)</th>
                <th>Tensão com carga(V)</th>
                <th>Resitência de carga(ohm)</th>
                <th>Resistência interna(ohm)</th>
            </tr>
            </thead>
            <tbody>
                 
            @foreach($medicoes as $medicao)
            <tr>
                <td>{{$medicao->pilha_bateria}}</td>
                <td>{{number_format($medicao->tensao_nominal,1,'.','')}}</td>
                <td>{{$medicao->capacidae_corrente}}</td>
                <td>{{$medicao->tensao_sem_carga}}</td>
                <td>{{$medicao->tensao_com_carga}}</td>
                <td>{{$medicao->resistencia_carga}}</td>
                <td>{{number_format($medicao->resistencia_interna,3,'.','')}}</td>

            </tr>

            @endforeach
          </tbody> 
        </table>
    </main>
    
@endsection

@section('medicoes')
    
<h4>medicoes</h4>

@endsection 

resources/views/pagina1.blade.php
@extends('templates.base')

@section('conteudo')
    <h2> página 1</h2>
    <hr>
@endsection

@section('rodape')
  <h4>rodapé da pagina 1</h4>

  @endsection

resources/views/pagina2.blade.php
@extends('templates.base')

@section('conteudo')
    <h2> página 2</h2>
    <hr>
@endsection

@section('rodape')
  <h4>rodapé da pagina 2</h4>

  @endsection

resources/views/principal.blade.php
@extends('templates.base')

@section('conteudo')
    <h2> página principal </h2>
    <hr>
@endsection

@section('rodape')
  <h4>rodapé da pagina principal</h4>

  @endsection

resources/views/principalBaterias.blade.php
@extends('templates.base') 
@section('conteudo')



    <main>
        <h1 class="h1">Turma: 2D3 - Grupo 1</h1>
        <h2 class="h2">Participantes:</h2>
        <hr>
        <table class="table table-striped table-bordered">
            <tr>
                <th>Matrículas</th>
                <th>Nome</th>
                <th>Função</th>
            </tr>


             <tr>
                <td>0072523</td>
                <td>Maria Eduarda da Costa Cassiano</td>
                <td>Gerente</td>
            </tr>


             <tr>
                <td>0056611</td>
                <td>Jean Carlos Silva de Oliveira</td>
                <td>Editor html</td>
            </tr>

             <tr>
                <td>0073450</td>
                <td>Alice Fernandes da Silva</td>
                <td>Medição</td>
            </tr>
            <tr>
                <td>0072563</td>
                <td>Danilo de Castro Macedo</td>
                <td>Editor html</td>
            </tr>




           
           
            <tr>
                <td>0066057</td>
                <td>Thiago Bekrman Silva Rocha</td>
                <td>Medição</td>
            </tr>
           
        </table>
        <img class="grupo" src="imgs/estudantes.jpeg" alt="Componentes do grupo">
    </main>
</body>
</html>

@endsection

@section('rodape')
    
<h4>jeanzin do 7</h4>

@endsection 

resources/views/procedimento.blade.php
@extends('templates.base') 
@section('conteudo')







<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Baterias</title>


    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="../css/estilos.css">
</head>
<body>
    <header>
        <h1>Baterias</h1>
    </header>

    <nav>
        <ul>
            <li><a href="../index.html">voltar para página principal</a></li>
        </ul>
    </nav>

    <main>
        <h1>Procedimento</h1>
        <hr>
        <h2>Medições:</h2>
        <p>
            Durante a aula de eletroeletrônica/programação em automação do dia 14/07, realizamos as medições das tensões de cada bateria/pilha escolhida pelo professor para realização do trabalho, o primeiro
            passo foi medir as pilhas e logo depois as baterias utilizando o multímetro, logo depois começamos as medições das baterias/pilhas com o Registor e para medir com o Registor precisamos mudar de
            resistência para tensão, anotamos os resultados da medições e conseguimos concluir que a diferença que com o Registor a pilha/bateria descarrega(cai pra zero mais rápido) e da uma estabilidade.
        </p>
        <h3>Tabela de medições:</h3>
        <p>
            Usando o código java do professor como exemplo nós montamos um código capaz de preencher a tabela com as imformações de medição das pilhas e baterias. Para não precisarmos fazer o calculo manual das
            resistências internas das pilhas e baterias nós usamos o mesmo código para fazer o cálculo e automaticamente o imprimir na tabela com o resto das informações.
        </p>
    </main>
</body>
</html>
@endsection

@section('rodape')
    
<h4>Procedimento</h4>

@endsection 

resources/views/templates/base.blade.php
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bateriasaravel</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ asset('css/estilos.css') }}">
</head>

<body>
    <div class="container-md">
        <h1>Baterias Laravel</h1>
        <hr>
        <nav>
            <ul>
                <li><a href="{{ route('/') }}">Início</a></li>
                <li><a href="{{ route('teoria') }}">Teoria</a></li>
                <li><a href="{{ route('procedimento') }}">Procedimento</a></li>
                <li><a href="{{ route('medicoes') }}">Medições</a></li>
                <li><a href="{{ route('conclusoes') }}">Conclusões</a></li>
            </ul>
        </nav>

        @yield("conteudo")
        <div class="rodape container-md">
            @yield("rodape")
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>

</html>

resources/views/teoria.blade.php
@extends('templates.base') 
@section('conteudo')




<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Baterias</title>


    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="../css/estilos.css">
</head>
<body>
    <header>
        <h1>Baterias</h1>
    </header>

    <nav>
        <ul>
            <li><a href="../index.html">voltar para página principal</a></li>
        </ul>
    </nav>

    <main>
        <h1>Teoria</h1>
        <hr>
        <h2>Descrição das pilhas:</h2>
        <p>
            <h5>Resistência e Resistência Interna:</h5>
A resistência é uma propriedade elétrica que descreve a oposição que um material oferece à passagem de corrente elétrica. É medida em ohms (Ω) e determina a dificuldade que os elétrons encontram para se movimentarem através de um condutor. A resistência interna, por sua vez, refere-se à resistência presente dentro de uma fonte de energia, como uma bateria ou uma célula. Essa resistência interna pode resultar na queda de tensão e na redução da eficiência da fonte ao fornecer corrente a um circuito externo.

<h5>Multímetro:</h5>
O multímetro é uma ferramenta de teste elétrico versátil e amplamente utilizada para medir grandezas elétricas, como tensão (voltagem), corrente e resistência. Ele possui diferentes escalas e modos de operação para se adequar às diversas medições em circuitos eletrônicos e elétricos.

<h5>Tensão, Tensão V e Tensão E:</h5>
A tensão, também conhecida como diferença de potencial, é uma medida da energia elétrica por unidade de carga em um circuito. Ela é responsável por impulsionar o fluxo de elétrons em um circuito, criando um movimento de corrente. A tensão é medida em volts (V).

"Tensão V" é uma forma comum de se referir à tensão aplicada ou medida em um componente específico ou ponto de interesse em um circuito.

"Tensão E" é frequentemente usada para representar a tensão da fonte de energia, como a tensão fornecida por uma bateria ou uma fonte de alimentação.

<h5>Resistor:</h5>
Um resistor é um componente eletrônico projetado para ter uma resistência elétrica específica. Ele é usado para controlar o fluxo de corrente em um circuito, limitar a corrente elétrica ou dividir a tensão. Os resistores são identificados por suas marcas de cores ou valores de resistência em ohms.

<h5>Vida útil de uma bateria:</h5>
A vida útil de uma bateria se refere ao período em que a bateria é capaz de fornecer energia de forma satisfatória para um dispositivo específico. Essa duração pode variar dependendo do tipo de bateria, do uso do dispositivo e das condições de armazenamento. Com o tempo e uso repetido, a capacidade da bateria diminui gradualmente até atingir um ponto em que a energia fornecida é insuficiente, e a bateria precisa ser recarregada ou substituída.

Em resumo, resistência é a oposição ao fluxo de corrente elétrica, enquanto a resistência interna refere-se à resistência presente em uma fonte de energia. O multímetro é uma ferramenta para medir grandezas elétricas. A tensão é a diferença de potencial elétrico, medida em volts. O resistor é um componente eletrônico que controla a corrente em um circuito. A vida útil de uma bateria é o período em que ela pode fornecer energia suficiente para um dispositivo.
        </p>
    </main>
</body>
</html>

@endsection

@section('rodape')
    
<h4>Procedimento</h4>

@endsection 